env:
  - PHP_VERSION=8.0
    - SITEID=odsg

dist: focal
language: php
cache:
  directories:
  - $HOME/.composer

php:
  - $PHP_VERSION

# Make sure we have a recent version of docker-compose.
addons:
  apt:
    packages:
      - docker-compose

services:
  - docker

before_script:
  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Install the AWS CLI and login to the ECR. Credentials are secrets set via the UI.
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
  - aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin public.ecr.aws/unocha

  - cd ${TRAVIS_BUILD_DIR}

  # This is failing with 'The command failed and exited with 123 during .
  # # Check the docker images we want actually exists.
  # - grep 'unocha/unified-builder:' ./docker/Dockerfile | awk '{print $2}' | xargs docker pull
  # - grep 'unocha/php-k8s:' ./docker/Dockerfile | awk '{print $2}' | xargs docker pull

  # Get docker information.
  - docker version
  - docker-compose version

  # Ensure the PHP environment is ready.
  - phpenv rehash

script:
  - cd ${TRAVIS_BUILD_DIR}

  - set -e
  # PHP linting
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - test ! -d ./html/themes/custom || find -L ./html/themes/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - set +e

  # Build local image.
  - make

  # Create the site and support containers.
  - docker-compose -f ./tests/docker-compose.yml up -d

  # Dump some information about the created containers.
  - docker ps -a

  # Wait a bit for containers to be ready.
  - sleep 10

  # Install the dev dependencies.
  - docker exec -it -w /srv/www "${SITEID}-site" sh -c "composer install"

  # Check coding standards.
  - docker exec -it -u appuser -w /srv/www "${SITEID}-site" ./vendor/bin/phpcs -p --report=full --standard=phpcs.xml ./html/modules/custom
  - docker exec -it -u appuser -w /srv/www "${SITEID}-site" ./vendor/bin/phpcs -p --report=full --standard=phpcs.xml ./html/themes/custom

  # Install the site with existing config.
  - docker exec -it "${SITEID}-site" drush -y si --existing-config minimal install_configure_form.enable_update_status_emails=NULL
  - docker exec -it "${SITEID}-site" drush -y en dblog
  - docker exec -it -w /srv/www "${SITEID}-site" drush -y cset system.site uuid $(grep uuid ./config/system.site.yml | awk '{print $2}')
  - docker exec -it "${SITEID}-site" drush -y cim --source=/srv/www/config
  - docker exec -it "${SITEID}-site" drush php-eval 'node_access_rebuild();'
  - docker exec -it "${SITEID}-site" drush cr
  - docker exec -it "${SITEID}-site" drush en yaml_content -y
  - docker exec -it "${SITEID}-site" drush yaml-content-import /srv/www/tests

  # Trying without chrome and the specialized ports.
  # # Chrome headless
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # - sleep 5

  # Test
  # - DTT_BASE_URL=http://127.0.0.1:8080 DTT_API_URL=http://localhost:9222 ./vendor/bin/phpunit --debug --testsuite=existing-site,existing-site-javascript 
  - docker exec -it -w /srv/www "${SITEID}-site" /srv/www/vendor/bin/phpunit --debug --colors --testsuite=existing-site,existing-site-javascript HomePageTest

after_success:
  - cd $TRAVIS_BUILD_DIR
  - killall -9 php
  - echo "The tests completed without errors."

after_failure:
  - echo "The tests failed. Please check the output above for problems."
