_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 37a45430-1a7f-49a2-9524-23c22aef597d
name: 'OCHA Donor Support Group'
mail: admin@odsg.unocha.org
slogan: ''
page:
  403: ''
  404: /node/100
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
